/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sofka.frowFinal;

import org.junit.Test;
import static org.junit.Assert.*;

public class ProductoAplicacionTest {
    @Test public void testSomeLibraryMethod() {
        ProductoAplicacion classUnderTest = new ProductoAplicacion();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
